name = "release-toolkit-app"
main = "dist/index.mjs"

compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_APP_ID = "3589117"

# Private key 通过以下命令设置：
# cd packages/app-server
# cat release-toolkit.2026-05-03.private-key.pem | npx wrangler secret put GITHUB_APP_PRIVATE_KEY
